### ISSUE TITLE
Why write tmp files?

### ISSUE THREAD

**Issue by florianbepunkt** [CodeDaraW/node-pdftocairo#13]
Is it possible to read directly from stdout and return a buffer instead of writing a tmp file?

**Comment by CodeDaraW** [comment]
In many cases the output may be multiple files, it's not easy to recognize the stdout stream as individual files.

Anyway, writing temp files is okay, I have been doing this for a long time in production and it works fine.

**Comment by florianbepunkt** [comment]
Valid point. Thank you.
