### ISSUE TITLE
Not able to run the code in the aws lambda server 

### ISSUE THREAD

**Issue by primosoft-dev-2** [CodeDaraW/node-pdftocairo#164]
Hi, below is the function I am using to generate a png from the pdf's first-page buffer. it is working fine on my local server but not working on the lambda server. Can we use this library in the lambda server?
```
 await input(firstPageBuffer, {
   format: "png",
    singlefile: true,
 }).output(firstPagePath);
```
Thanks.

**Comment by CodeDaraW** [comment]
I'm not familiar with AWS Lambda, but can you provide more info about the problem?   
Such as printed error logs or something, so that i may find the cause.

**Comment by CodeDaraW** [comment]
btw, have u installed pdftocairo/Poppler in the server?

**Comment by primosoft-dev-2** [comment]
Thanks for the response.
No, I haven't installed the pdftocairo/Poppler at first(at the time of raising the issue).
 But now I have installed the libraries using the lambda layers.
 But still getting some errors related to to the shared libraries like below
 
 ` error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory`

**Comment by primosoft-dev-2** [comment]
But your library is not handling those errors, i am getting the undefined instead of the correct error message while using you library. so i wrote my own code to check for the error codes and issue. 
like below:
`
const ls = spawn('./nodejs/pdftocairo', ['-v']);

    ls.stdout.on('data', (data) => {
      console.log(`stdout: ${data}`);
    });

    ls.stderr.on('data', (data) => {
      console.error(`stderr: ${data}`);
    });

    ls.on('close', (code) => {
      console.log(`child process exited with code ${code}`);
    });
`

**Comment by primosoft-dev-2** [comment]
So my problem is with the installation but not with the library code, 
but still, it would be great if you can add the proper error handling based on the child process exit code.
Thanks.

**Comment by CodeDaraW** [comment]
Yeah, thanks for pointing out the problem. I found the cause of getting `undefined` instead of real error message is that not all exit codes are listed in `ERROR_MESSAGES` map. So i choose to use `stderr` data directly.

See #167, and try the latest version (1.2.0) of the npm package please.

**Comment by CodeDaraW** [comment]
> Thanks for the response. No, I haven't installed the pdftocairo/Poppler at first(at the time of raising the issue). But now I have installed the libraries using the lambda layers. But still getting some errors related to to the shared libraries like below
> 
> ` error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory`

and have u solved the problem? It seems that the underlying operating system of AWS Lambda has the error `so` library.

**Comment by primosoft-dev-2** [comment]
> > Thanks for the response. No, I haven't installed the pdftocairo/Poppler at first(at the time of raising the issue). But now I have installed the libraries using the lambda layers. But still getting some errors related to to the shared libraries like below
> > ` error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory`
> 
> and have u solved the problem? It seems that the underlying operating system of AWS Lambda has the error `so` library.

Yes, I fixed my AWS Lambda issue by manually copying all the required libraries. Now, thumbnail generation for the PDFs is working fine in the lambda server.

**Comment by primosoft-dev-2** [comment]
> 1.2.0

Just checked the new version. It's working fine, showing the exact error message.
You can close the Issue.
Thank you.

**Comment by CodeDaraW** [comment]
Great!
