### ISSUE TITLE
Converting PDF to multipage TIFF

### ISSUE THREAD

**Issue by joshReder82** [CodeDaraW/node-pdftocairo#65]
Is it possible to convert PDF to multi-page TIFF? I always get multiple images for each page of the pdf.
thanks

**Comment by CodeDaraW** [comment]
Sorry I'm not familiar with tiff, can u show me the full command of converting pdf to tiff with shell and pdftocario for your use case?

**Comment by joshReder82** [comment]
Hello, what I try is that if a pdf file has several pages, it does not generate a .tiff image for each page of the pdf, the question is if there is any way to do it, that a single .tiff contains all the images

```const path = require('path');

const pdft = require('node-pdftocairo');

async function getTif() {
  const inputPath = path.join(__dirname, '/DOCUMENTOS/PRUEBA.pdf');

  const options = {
    format: 'tiff',
    // nocrop: true,
    resolution: {
      x: 300,
      y: 300
    },
    mono: true,
  };
  try {
    await pdft.input(inputPath, options).output(__dirname + '/PRUEBA');
  } catch (error) {
    console.log(error);
  }
}

getTif();

```

the file PRUEBA.pdf, has 5 pages, the result of the execution is
-PRUEBA-1.tiff
-PRUEBA-2.tiff
-PRUEBA-3.tiff
-PRUEBA-4.tiff
-PRUEBA-4.tiff
there is no way that it just returns a PRUEBA.tiff with all the pages in a single file, as a compression type, thanks

**Comment by CodeDaraW** [comment]
Refer to [doc](http://manpages.ubuntu.com/manpages/bionic/man1/pdftocairo.1.html), `pdftocairo` does not support this.  
Maybe u can find some other libs do this.

**Comment by joshReder82** [comment]
ok, thanks
